import { useState } from "react";
import { Header } from "../components/layout/Header";
import { Icon } from "../components/ui/Icon";
import { Avatar, Badge, Button, Card, IconButton } from "../components/ui/Primitives";
import { ToastStack } from "../components/ui/Components";
import type { Order, ToastItem } from "../types";

const metrics = [
  { label: "Net revenue", value: "$48,290", change: "+12.8%", note: "vs. last month", icon: "solar:wad-of-money-bold-duotone", color: "var(--primary)" },
  { label: "Active customers", value: "2,481", change: "+8.2%", note: "vs. last month", icon: "solar:users-group-rounded-bold-duotone", color: "var(--secondary)" },
  { label: "Conversion rate", value: "6.24%", change: "+2.1%", note: "vs. last month", icon: "solar:graph-up-bold-duotone", color: "var(--accent)" },
  { label: "Avg. order value", value: "$184.60", change: "+4.6%", note: "vs. last month", icon: "solar:cart-large-4-bold-duotone", color: "var(--warning)" },
];

const orders: Order[] = [
  { id: "#10482", customer: "Maya Chen", initials: "MC", product: "Studio annual", amount: "$1,240.00", status: "Paid", date: "Today, 10:42" },
  { id: "#10481", customer: "Omar Haddad", initials: "OH", product: "Team monthly", amount: "$480.00", status: "Pending", date: "Today, 09:18" },
  { id: "#10480", customer: "Elena Rossi", initials: "ER", product: "Starter annual", amount: "$290.00", status: "Paid", date: "Yesterday" },
  { id: "#10479", customer: "Jon Bell", initials: "JB", product: "Team monthly", amount: "$480.00", status: "Refunded", date: "Yesterday" },
];

export function Dashboard() {
  const [toasts, setToasts] = useState<ToastItem[]>([]);
  const pushToast = (title: string, description: string, tone: ToastItem["tone"] = "success") => {
    const id = Date.now();
    setToasts((current) => [...current, { id, title, description, tone }]);
    window.setTimeout(() => setToasts((current) => current.filter((item) => item.id !== id)), 4200);
  };
  return <main className="page-content">
    <Header eyebrow="Workspace / Overview" title="صباح الخير, فؤاد" description="Here’s a calm view of what’s moving across your workspace today." actions={<><Button variant="outline" leftIcon="solar:download-minimalistic-linear" onClick={() => pushToast("Export queued", "Your CSV will be ready in a moment.", "info")}>Export</Button><Button leftIcon="solar:add-circle-linear" onClick={() => pushToast("Quick action ready", "This is a demo interaction for the showcase.")}>Create report</Button></>} />
    <section className="metric-grid" aria-label="Key metrics">{metrics.map((metric) => <Card key={metric.label} className="metric-card" style={{ "--metric-color": metric.color } as React.CSSProperties}><div className="metric-top"><span className="metric-label">{metric.label}</span><span className="metric-icon"><Icon icon={metric.icon} size={20} /></span></div><div className="metric-value">{metric.value}</div><div className="metric-foot"><span className="metric-trend"><Icon icon="solar:arrow-up-linear" size={13} /> {metric.change}</span><span className="muted">{metric.note}</span></div></Card>)}</section>
    <section className="dashboard-grid">
      <Card className="chart-wrap"><div className="chart-header"><div><div className="section-kicker">Revenue overview</div><div className="chart-amount">$128,240.40 <span style={{ color: "var(--success)", fontSize: 12, fontWeight: 750 }}>+14.6%</span></div></div><select className="select" style={{ width: 108, height: 34, fontSize: 11 }} aria-label="Date range"><option>Last 30 days</option><option>Last 90 days</option></select></div><div className="chart-area"><svg className="chart-line" viewBox="0 0 800 220" preserveAspectRatio="none" aria-label="Revenue trend chart" role="img"><path d="M0 164 L48 149 L96 160 L152 118 L208 136 L264 94 L320 108 L376 62 L432 78 L488 45 L544 68 L600 28 L664 48 L728 15 L800 32" fill="none" stroke="var(--primary)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /><path d="M0 190 L48 181 L96 185 L152 161 L208 172 L264 141 L320 152 L376 122 L432 135 L488 107 L544 120 L600 91 L664 106 L728 82 L800 94" fill="none" stroke="var(--secondary)" strokeWidth="2" strokeDasharray="5 7" strokeLinecap="round" /></svg></div><div className="chart-legend"><span><i className="legend-dot" /> Current period</span><span><i className="legend-dot secondary" /> Previous period</span></div></Card>
      <Card className="card-pad"><div className="section-label"><div><div className="section-kicker">Team activity</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>What’s happening</h2></div><IconButton label="More activity" icon="solar:menu-dots-bold" /></div><div style={{ display: "grid", gap: 18, marginBlockStart: 24 }}>{[{ icon: "solar:palette-bold-duotone", text: "Noura updated the Button component", time: "12 min ago", tone: "var(--primary)" }, { icon: "solar:users-group-rounded-bold-duotone", text: "Omar joined the design review", time: "48 min ago", tone: "var(--secondary)" }, { icon: "solar:check-circle-bold-duotone", text: "Release v2.4 was published", time: "2 hrs ago", tone: "var(--accent)" }, { icon: "solar:chat-round-bold-duotone", text: "Maya left a comment on Tokens", time: "3 hrs ago", tone: "var(--warning)" }].map((item) => <div key={item.text} style={{ display: "flex", gap: 11, alignItems: "flex-start" }}><span style={{ display: "grid", placeItems: "center", flex: "0 0 auto", width: 31, height: 31, borderRadius: 10, color: item.tone, background: `color-mix(in srgb, ${item.tone} 12%, transparent)` }}><Icon icon={item.icon} size={16} /></span><div><div style={{ color: "var(--text-soft)", fontSize: 11, lineHeight: 1.4 }}>{item.text}</div><div style={{ marginBlockStart: 4, color: "var(--text-faint)", fontSize: 10 }}>{item.time}</div></div></div>)}</div></Card>
    </section>
    <section className="dashboard-grid" style={{ marginBlockStart: 18 }}>
      <Card><div className="card-pad section-label"><div><div className="section-kicker">Commerce</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Recent orders</h2></div><Button variant="ghost" size="sm" rightIcon="solar:arrow-right-linear" onClick={() => pushToast("Orders view", "A full orders module can build on this table.", "info")}>View all</Button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Product</th><th>Amount</th><th>Status</th><th>Date</th><th aria-label="Actions" /></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><div className="order-cell"><Avatar initials={order.initials} size="sm" /><span>{order.customer}<small style={{ display: "block", marginBlockStart: 3, color: "var(--text-faint)", fontSize: 10 }}>{order.id}</small></span></div></td><td>{order.product}</td><td style={{ color: "var(--text)", fontWeight: 750 }}>{order.amount}</td><td><Badge tone={order.status === "Paid" ? "success" : order.status === "Pending" ? "warning" : "danger"}>{order.status}</Badge></td><td>{order.date}</td><td><IconButton label={`Actions for ${order.id}`} icon="solar:menu-dots-bold" /></td></tr>)}</tbody></table></div></Card>
      <Card className="card-pad"><div className="section-label"><div><div className="section-kicker">Shortcuts</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Quick actions</h2></div><Icon icon="solar:bolt-circle-bold-duotone" size={22} color="var(--warning)" /></div><div style={{ display: "grid", gap: 9, marginBlockStart: 18 }}><Button variant="outline" className="btn-block" leftIcon="solar:palette-linear" onClick={() => pushToast("System opened", "Jumping to the component showcase.", "info")}>Browse components</Button><Button variant="outline" className="btn-block" leftIcon="solar:users-group-rounded-linear" onClick={() => pushToast("Invite link copied", "Share it with a teammate when ready.")}>Invite a teammate</Button><Button variant="outline" className="btn-block" leftIcon="solar:settings-linear" onClick={() => pushToast("Preferences", "Theme and layout settings live in the topbar.", "warning")}>Workspace settings</Button></div><div style={{ display: "flex", alignItems: "center", gap: 8, marginBlockStart: 25, padding: 12, borderRadius: 13, color: "var(--text-soft)", background: "var(--surface-2)", fontSize: 11, lineHeight: 1.5 }}><Icon icon="solar:info-circle-bold-duotone" size={17} color="var(--info)" />Everything here is built from Aurora primitives.</div></Card>
    </section>
    <ToastStack items={toasts} onDismiss={(id) => setToasts((current) => current.filter((item) => item.id !== id))} />
  </main>;
}
