import { useState } from "react";
import { Header } from "../components/layout/Header";
import { Icon } from "../components/ui/Icon";
import { Avatar, Badge, Button, Card, Divider, IconButton, Input } from "../components/ui/Primitives";
import { Checkbox, CodeInspectorModal, Dropdown, Drawer, EmptyState, FormField, Modal, Radio, Select, Spinner, Switch, Tabs, Textarea, ToastStack, Tooltip } from "../components/ui/Components";
import type { ToastItem } from "../types";

const codeSnippets = {
  button: `<Button variant="primary" size="md" leftIcon="solar:add-circle-linear">\n  Create project\n</Button>`,
  field: `<FormField label="Email" required description="Used for product updates.">\n  <Input placeholder="you@company.com" />\n</FormField>`,
  badge: `<Badge tone="success">Published</Badge>`,
};

export function DesignSystem() {
  const [code, setCode] = useState<{ title: string; content: string } | null>(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [notifications, setNotifications] = useState<ToastItem[]>([]);
  const [tab, setTab] = useState("Overview");
  const [checked, setChecked] = useState(true);
  const [radio, setRadio] = useState(true);
  const [toggled, setToggled] = useState(true);
  const pushToast = (title: string, description: string, tone: ToastItem["tone"] = "success") => {
    const id = Date.now();
    setNotifications((current) => [...current, { id, title, description, tone }]);
    window.setTimeout(() => setNotifications((current) => current.filter((item) => item.id !== id)), 4200);
  };
  const inspect = (title: string, content: string) => setCode({ title, content });

  return <main className="page-content">
    <Header eyebrow="Workspace / Library" title="Design system" description="Aurora is a small, opinionated language for focused SaaS interfaces. Every preview below is live, composable, and ready to extend." actions={<Button leftIcon="solar:book-2-linear" onClick={() => pushToast("Documentation", "The full contribution guide is coming soon.", "info")}>Read the guide</Button>} />
    <div className="showcase-grid">
      <Card className="showcase-intro"><div className="showcase-intro-copy"><div className="section-kicker">Aurora / v0.1</div><h2 className="page-title" style={{ fontSize: 27, marginBlockStart: 9 }}>Small pieces, clear rhythm.</h2><p className="page-description" style={{ marginBlockStart: 10 }}>A friendly, compact system with enough character to be remembered and enough restraint to disappear behind the work.</p><div className="showcase-chip-row"><span className="showcase-chip">Desktop first</span><span className="showcase-chip">RTL ready</span><span className="showcase-chip">Token driven</span><span className="showcase-chip">Reduced motion</span></div></div><div style={{ display: "grid", placeItems: "center", width: 150, height: 150, flex: "0 0 auto", borderRadius: 38, color: "#fff", background: "linear-gradient(145deg, var(--secondary), var(--primary))", boxShadow: "0 24px 40px color-mix(in srgb, var(--secondary) 22%, transparent)", transform: "rotate(5deg)" }}><Icon icon="solar:layers-minimalistic-bold-duotone" size={70} /></div></Card>

      <Card className="showcase-section wide"><div className="section-label"><div><div className="section-kicker">Foundations</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Colors & tokens</h2></div><button className="code-button" onClick={() => inspect("CSS token layer", `:root {\n  --primary: #ef654d;\n  --secondary: #7667e8;\n  --accent: #37b7a1;\n  --radius-md: 14px;\n  --shadow-soft: 0 12px 32px rgba(...);\n}`)}>View token code <Icon icon="solar:code-square-linear" size={15} /></button></div><div className="color-grid"><div className="color-swatch" style={{ background: "var(--primary)" }}>Primary<br /><span style={{ opacity: .7 }}>#EF654D</span></div><div className="color-swatch" style={{ background: "var(--secondary)" }}>Secondary<br /><span style={{ opacity: .7 }}>#7667E8</span></div><div className="color-swatch" style={{ background: "var(--accent)" }}>Accent<br /><span style={{ opacity: .7 }}>#37B7A1</span></div><div className="color-swatch" style={{ background: "var(--success)" }}>Success<br /><span style={{ opacity: .7 }}>#229C72</span></div><div className="color-swatch" style={{ background: "var(--warning)" }}>Warning<br /><span style={{ opacity: .7 }}>#CE851A</span></div></div><div className="token-list"><div className="token-row"><span>Space scale</span><span className="token-value">4 · 8 · 12 · 16 · 24 · 32</span></div><div className="token-row"><span>Radius language</span><span className="token-value">10 / 14 / 20 / 28px</span></div><div className="token-row"><span>Motion</span><span className="token-value">140 / 220 / 360ms</span></div></div></Card>

      <Card className="showcase-section"><div className="section-label"><div><div className="section-kicker">Foundations</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Typography</h2></div><button className="code-button" onClick={() => inspect("Typography tokens", `--font-display: "Space Grotesk";\n--font-body: "DM Sans";`)}>View code <Icon icon="solar:code-square-linear" size={15} /></button></div><div><div className="type-sample"><span style={{ fontFamily: "Space Grotesk", fontSize: 25, fontWeight: 700, letterSpacing: "-.05em" }}>Display</span><span className="type-meta">32 / 700</span></div><div className="type-sample"><span style={{ fontSize: 21, fontWeight: 750 }}>Heading one</span><span className="type-meta">24 / 750</span></div><div className="type-sample"><span style={{ fontSize: 14 }}>Body copy for product interfaces</span><span className="type-meta">14 / 400</span></div><div className="type-sample"><span style={{ fontSize: 11, color: "var(--text-soft)" }}>Caption · supporting information</span><span className="type-meta">11 / 600</span></div></div></Card>

      <Card className="showcase-section"><div className="section-label"><div><div className="section-kicker">Action</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Buttons</h2></div><button className="code-button" onClick={() => inspect("Button.tsx", codeSnippets.button)}>View code <Icon icon="solar:code-square-linear" size={15} /></button></div><div className="preview-column"><div className="preview-row"><Button>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="outline">Outline</Button></div><div className="preview-row"><Button variant="ghost" leftIcon="solar:magic-stick-3-linear">Ghost</Button><Button variant="danger" leftIcon="solar:trash-bin-trash-linear">Danger</Button><Button variant="success" leftIcon="solar:check-circle-linear">Success</Button></div><div className="preview-row"><Button size="sm">Small</Button><Button>Medium</Button><Button size="lg">Large</Button><Button loading>Saving</Button></div></div></Card>

      <Card className="showcase-section"><div className="section-label"><div><div className="section-kicker">Content</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Badges & avatars</h2></div><button className="code-button" onClick={() => inspect("Badge.tsx", codeSnippets.badge)}>View code <Icon icon="solar:code-square-linear" size={15} /></button></div><div className="preview-column"><div className="preview-row"><Badge tone="success">Published</Badge><Badge tone="warning">Needs review</Badge><Badge tone="danger">At risk</Badge><Badge tone="info">In progress</Badge><Badge>Draft</Badge></div><Divider /><div className="preview-row"><Avatar initials="NS" size="sm" /><Avatar initials="MC" /><Avatar initials="OH" size="lg" /><div style={{ display: "flex" }}><Avatar initials="NS" size="sm" /><Avatar initials="MC" size="sm" /><Avatar initials="OH" size="sm" /></div></div></div></Card>

      <Card className="showcase-section"><div className="section-label"><div><div className="section-kicker">Inputs</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Form elements</h2></div><button className="code-button" onClick={() => inspect("FormField.tsx", codeSnippets.field)}>View code <Icon icon="solar:code-square-linear" size={15} /></button></div><div className="preview-column"><FormField label="Workspace name" required description="A short name teammates will recognize."><Input placeholder="e.g. Northstar" /></FormField><FormField label="Plan" error="Choose a plan to continue."><Select defaultValue=""><option value="" disabled>Select a plan</option><option value="starter">Starter</option><option value="studio">Studio</option></Select></FormField><FormField label="Notes"><Textarea placeholder="Add a little context..." /></FormField></div></Card>

      <Card className="showcase-section"><div className="section-label"><div><div className="section-kicker">Selection</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Controls</h2></div></div><div className="preview-column"><Checkbox label="Keep me updated" checked={checked} onChange={setChecked} /><Radio label="Monthly billing" checked={radio} onChange={() => setRadio(true)} /><Radio label="Annual billing" checked={!radio} onChange={() => setRadio(false)} /><Switch label="Smart suggestions" checked={toggled} onChange={setToggled} /></div></Card>

      <Card className="showcase-section wide"><div className="section-label"><div><div className="section-kicker">Navigation</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Tabs, dropdowns & tooltips</h2></div><button className="code-button" onClick={() => inspect("Navigation primitives", `<Tabs items={["Overview", "Activity"]} />\n<Dropdown label="Filter" items={[...]} />`)}>View code <Icon icon="solar:code-square-linear" size={15} /></button></div><div style={{ display: "grid", gridTemplateColumns: "minmax(220px, 1fr) minmax(200px, .55fr)", gap: 18, alignItems: "center" }}><Tabs items={["Overview", "Activity", "Settings"]} active={tab} onChange={setTab} /><div className="preview-row" style={{ marginBlockStart: 0 }}><Dropdown label="Filter" items={["All items", "Published", "Drafts"]} /><Tooltip label="This is a Solar Duo icon"><IconButton label="Help" icon="solar:question-circle-bold-duotone" /></Tooltip></div></div><div style={{ marginBlockStart: 18, padding: 14, borderRadius: 12, color: "var(--text-soft)", background: "var(--surface-2)", fontSize: 12 }}>Showing the <strong style={{ color: "var(--text)" }}>{tab.toLowerCase()}</strong> tab state.</div></Card>

      <Card className="showcase-section wide"><div className="section-label"><div><div className="section-kicker">Data</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Table & empty state</h2></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Component</th><th>Owner</th><th>Coverage</th><th>Status</th><th /></tr></thead><tbody>{[["Button", "Noura Salem", "98%", "Published"], ["Data table", "Maya Chen", "84%", "In review"], ["Modal", "Omar Haddad", "76%", "Draft"]].map(([component, owner, coverage, status]) => <tr key={component}><td style={{ color: "var(--text)", fontWeight: 750 }}>{component}</td><td><div className="order-cell"><Avatar initials={owner.split(" ").map((part) => part[0]).join("")} size="sm" />{owner}</div></td><td>{coverage}</td><td><Badge tone={status === "Published" ? "success" : status === "Draft" ? "neutral" : "warning"}>{status}</Badge></td><td><IconButton label={`More actions for ${component}`} icon="solar:menu-dots-bold" /></td></tr>)}</tbody></table></div><div style={{ marginBlockStart: 22 }}><EmptyState title="No archived components" description="When a component is retired, it will appear here for reference." action={<Button variant="outline" size="sm" leftIcon="solar:archive-linear">View archive</Button>} /></div></Card>

      <Card className="showcase-section third"><div className="section-label"><div><div className="section-kicker">Feedback</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Modal</h2></div></div><p className="page-description" style={{ margin: 0 }}>Use for focused decisions that need a clear path forward.</p><div className="preview-row"><Button variant="outline" onClick={() => setModalOpen(true)}>Open modal</Button></div></Card>
      <Card className="showcase-section third"><div className="section-label"><div><div className="section-kicker">Feedback</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Drawer</h2></div></div><p className="page-description" style={{ margin: 0 }}>Keep context visible when a task can live beside the page.</p><div className="preview-row"><Button variant="outline" onClick={() => setDrawerOpen(true)}>Open drawer</Button></div></Card>
      <Card className="showcase-section third"><div className="section-label"><div><div className="section-kicker">Feedback</div><h2 className="section-heading" style={{ marginBlockStart: 4 }}>Toast & loading</h2></div></div><p className="page-description" style={{ margin: 0 }}>Brief, useful feedback for actions that complete in place.</p><div className="preview-row"><Button variant="outline" onClick={() => pushToast("Changes saved", "Your component is now up to date.")}>Show toast</Button><Spinner /></div></Card>
    </div>
    <CodeInspectorModal open={Boolean(code)} onClose={() => setCode(null)} title={code?.title ?? "Code"} code={code?.content ?? ""} />
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Publish component"><p style={{ margin: 0, color: "var(--text-soft)", fontSize: 13, lineHeight: 1.7 }}>You’re about to publish <strong style={{ color: "var(--text)" }}>Button / v2.4</strong> to your team library. This keeps the current API and visual tokens intact.</p><div className="preview-row" style={{ justifyContent: "flex-end" }}><Button variant="ghost" onClick={() => setModalOpen(false)}>Cancel</Button><Button onClick={() => { setModalOpen(false); pushToast("Component published", "Button / v2.4 is live in the team library."); }}>Publish</Button></div></Modal>
    <Drawer open={drawerOpen} onClose={() => setDrawerOpen(false)} title="Component details"><div className="preview-column"><Badge tone="success">Published</Badge><h3 style={{ margin: 0, fontSize: 23, letterSpacing: "-.04em" }}>Button / v2.4</h3><p className="page-description" style={{ margin: 0 }}>A balanced action primitive with clear hierarchy, keyboard focus, and loading feedback.</p><Divider /><FormField label="Owner"><Input value="Noura Salem" readOnly /></FormField><FormField label="Release notes"><Textarea value="Added success variant and improved icon spacing." readOnly /></FormField><Button className="btn-block" onClick={() => { setDrawerOpen(false); pushToast("Review requested", "The team has been notified.", "info"); }}>Request review</Button></div></Drawer>
    <ToastStack items={notifications} onDismiss={(id) => setNotifications((current) => current.filter((item) => item.id !== id))} />
  </main>;
}
